[build]
  command = "npm run build"
  publish = ".next"
  ignore = "git diff --name-only $CACHED_COMMIT_REF $COMMIT_REF | tr -d '\n' | grep -q '^README.md$'"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Production deploy
[context.production]
  command = "npm run build"

# Deploy previews (PRs)
[context.deploy-preview]
  command = "npm run build"

# Branch deploys
[context.branch-deploy]
  command = "npm run build"